#!/usr/bin/env python3
"""FROZEN. Invariant burndown for the AlphaClimate risk engine.

Scored properties, not ground truth. There is no backtest, no historical loss
set and no calibration target anywhere in this repository, so accuracy is not
measurable here. What is measurable is whether the engine obeys the physical,
financial and mathematical properties it must obey to mean anything at all.

Score is `held / total`. Each invariant either returns a short detail string or
raises AssertionError with the numbers in the message.

DO NOT EDIT THIS FILE. It is restored from a frozen git ref before every
scoring run, so edits are reverted and recorded. Weakening a check does not
raise the score; it only shows up in the log as a tampering attempt.

Usage:  python3 -B research/invariants.py [--experiment N]
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import inspect
import json
import math
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "api"))

# --------------------------------------------------------------------------
# Frozen constants.
#
# These are copies, deliberately. compute.py holds its own versions and the
# agent may edit them; as far as scoring is concerned those are decoration.
# The comment carried across from compute.py:400-402 is the reason these are
# the right anchors: they are the only numbers in the repo argued from physical
# reality rather than fitted.
#
#   "These are physical bounds, not calibration targets. If a change trips one,
#    find the cause; do not widen the band."
# --------------------------------------------------------------------------

PLAUSIBLE_EAL_PCT = (0.0001, 0.10)
PLAUSIBLE_MEDIAN_ASSET_EAL_PCT = 0.02
MAX_SHARE_OF_ASSETS_ABOVE_5PCT = 0.25
MIN_ASSETS_WITH_LOSS = 6
MIN_PERILS_IN_ATTRIBUTION = 2
MIN_SWEEP_POINTS = 18
MIN_SWEEP_RANGE_RATIO = 1.2

# The eval passes its own Assumptions everywhere it touches finance, so moving
# the defaults in finance.py does not move the eval.
INS = dict(
    deductible_fraction=0.02,
    limit_fraction=0.80,
    coinsurance=0.10,
    premium_rate_on_eal=1.35,
)

SCENARIO = "ssp585"

_REG = []  # [(id, group, name, fn)]


def invariant(inv_id, group, name):
    def deco(fn):
        _REG.append((inv_id, group, name, fn))
        return fn
    return deco


# --------------------------------------------------------------------------
# The eval's own maths. Never imported from the engine: an engine that defines
# its own notion of correctness is not being tested.
# --------------------------------------------------------------------------

def ref_eal(rps, losses):
    """Expected annual loss by trapezoid over exceedance probability.

    The probability domain is [0, 1]. Anchored at p = 1 with zero loss, which
    is the assumption "events more frequent than the shortest modelled return
    period cause no damage". Flat tail beyond the longest return period.
    """
    ps = [1.0 / r for r in rps]
    total = 0.5 * losses[0] * (1.0 - ps[0])
    for i in range(len(ps) - 1):
        total += 0.5 * (losses[i] + losses[i + 1]) * (ps[i] - ps[i + 1])
    return total + losses[-1] * ps[-1]


def intensity_at(rps, ints, r):
    """Intensity at an arbitrary return period, interpolated in log-RP space.

    Same rule the engine already uses in loss_at_return_period.
    """
    if r <= rps[0]:
        return ints[0]
    if r >= rps[-1]:
        return ints[-1]
    for j in range(1, len(rps)):
        if r <= rps[j]:
            l0, l1 = math.log(rps[j - 1]), math.log(rps[j])
            t = (math.log(r) - l0) / (l1 - l0)
            return ints[j - 1] + t * (ints[j] - ints[j - 1])
    return ints[-1]


def refine(rps, ints, factor):
    """Subdivide every RP interval `factor` times, geometrically."""
    out_r, out_i = [], []
    for i in range(len(rps) - 1):
        for k in range(factor):
            f = k / float(factor)
            r = math.exp(math.log(rps[i]) + f * (math.log(rps[i + 1]) - math.log(rps[i])))
            out_r.append(r)
            out_i.append(intensity_at(rps, ints, r))
    out_r.append(rps[-1])
    out_i.append(ints[-1])
    return out_r, out_i


def with_step_knot(rps, ints, protection_rp):
    """Insert a zero-loss knot immediately below the protection standard.

    A defence built to a 1-in-N standard is a discontinuity. Without a knot at
    N the trapezoid spanning it carries half a step of loss that the defence
    is supposed to hold back.
    """
    if not protection_rp or protection_rp <= rps[0] or protection_rp >= rps[-1]:
        return list(rps), list(ints)
    k = protection_rp * (1.0 - 1e-9)
    pairs = sorted(zip(list(rps) + [k], list(ints) + [intensity_at(rps, ints, k)]))
    return [p[0] for p in pairs], [p[1] for p in pairs]


def frac_at_rp(pr, r):
    """Damage fraction of one peril result at an arbitrary return period."""
    rps, fr = pr.lc.return_periods, pr.lc.damage_fractions
    if not rps:
        return 0.0
    if r <= rps[0]:
        return fr[0]
    if r >= rps[-1]:
        return fr[-1]
    for j in range(1, len(rps)):
        if r <= rps[j]:
            l0, l1 = math.log(rps[j - 1]), math.log(rps[j])
            t = (math.log(r) - l0) / (l1 - l0)
            return fr[j - 1] + t * (fr[j] - fr[j - 1])
    return fr[-1]


def sig(x, digits=6):
    """Round to significant figures, for distinctness tests."""
    if x == 0:
        return 0.0
    return round(x, -int(math.floor(math.log10(abs(x)))) + (digits - 1))


# --------------------------------------------------------------------------
# Context: every model output the invariants need, computed once.
# Any exception in here aborts the run with score 0, deliberately: an engine
# that does not run is not an engine.
# --------------------------------------------------------------------------

class Ctx:
    def __init__(self):
        from app import compute, portfolio as pf
        from app.finance import Assumptions

        self.compute = compute
        self.pf = pf
        self.assumptions = Assumptions(**INS)

        self.assets = list(pf.DEMO_ASSETS)
        self.summ = compute.summary(SCENARIO)
        self.summ_126 = compute.summary("ssp126")
        self.summ_245 = compute.summary("ssp245")

        # Per-asset peril results, event perils only (permanent inundation is a
        # write-down, not an annual loss, and summary() excludes it too).
        self.perils = {}
        self.event_perils = {}
        for a in self.assets:
            prs = compute._asset_perils(a, SCENARIO)
            self.perils[a.id] = prs
            self.event_perils[a.id] = [r for r in prs if not r.permanent]

        self.by_id = {a.id: a for a in self.assets}
        self.rows = {r["id"]: r for r in self.summ["assets"]}

        # The raw sweep, recomputed here so distinctness and membership can be
        # tested. portfolio_spread() returns only the summary statistics.
        self.sweep = self._sweep()

        # Determinism probes. Each restores DEMO_ASSETS before returning.
        self.summ_repeat = compute.summary(SCENARIO)
        self.summ_reversed = self._with_assets(list(reversed(self.assets)))
        self.summ_doubled = self._with_assets(self._doubled(self.assets))
        self.summ_mutated = self._with_assets(self._mutated(self.assets))

    def _sweep(self):
        c, pf = self.compute, self.pf
        from app import hazard as hz
        vals = []
        n_variants = max((len(hz.variants(p)) for p in hz.PERILS), default=1)
        for sc in c.SPREAD_SCENARIOS:
            for vrank in range(max(1, n_variants)):
                for crank in range(3):
                    total = sum(c._asset_eal(a, sc, vrank, crank) for a in self.assets)
                    if total <= 0:
                        continue
                    vals.append(total)
        return vals

    def _with_assets(self, assets):
        pf = self.pf
        original = pf.DEMO_ASSETS
        try:
            pf.DEMO_ASSETS = assets
            return self.compute.summary(SCENARIO)
        finally:
            pf.DEMO_ASSETS = original

    @staticmethod
    def _doubled(assets):
        out = []
        for a in assets:
            b = copy.copy(a)
            b.value = a.value * 2
            b.annual_revenue = a.annual_revenue * 2
            b.debt = a.debt * 2
            b.annual_debt_service = a.annual_debt_service * 2
            out.append(b)
        return out

    @staticmethod
    def _mutated(assets):
        out = [copy.copy(a) for a in assets]
        out[0].value = 1.0
        return out

    def fin_for(self, asset):
        from app.finance import AssetFinancials
        return AssetFinancials(
            value=asset.value,
            annual_revenue=asset.annual_revenue,
            debt=asset.debt,
            annual_debt_service=asset.annual_debt_service,
        )

    def eal_of(self, asset_id):
        return sum(r.lc.eal for r in self.event_perils[asset_id])


# --------------------------------------------------------------------------
# 1. Integration and the loss curve
# --------------------------------------------------------------------------

FIXTURE_RPS = [2, 5, 10, 25, 50, 100, 250, 500, 1000]
FIXTURE_INTS = [1.0] * 9
FIXTURE_X = [0.0, 0.5, 1.0, 2.0]
FIXTURE_Y = [0.0, 0.25, 0.50, 0.70]
FIXTURE_VALUE = 1e8


@invariant("INT-DOMAIN", "integration",
           "expected loss integrates the full probability domain")
def _(c):
    from app.engine import loss_curve
    lc = loss_curve(FIXTURE_RPS, FIXTURE_INTS, FIXTURE_X, FIXTURE_Y, FIXTURE_VALUE)
    ref = ref_eal(lc.return_periods, lc.losses)
    assert abs(lc.eal - ref) <= 1e-9 * ref, (
        "fixture: eal {:,.0f} vs reference {:,.0f} ({:+.2%}); the probability "
        "band p in [{:.3f}, 1.0] carries no loss".format(
            lc.eal, ref, lc.eal / ref - 1.0, 1.0 / lc.return_periods[0])
    )
    bad = []
    for aid, prs in c.event_perils.items():
        for r in prs:
            ref = ref_eal(r.lc.return_periods, r.lc.losses)
            if ref > 0 and abs(r.lc.eal - ref) > 1e-9 * ref:
                bad.append("{}/{} {:+.1%}".format(aid, r.peril, r.lc.eal / ref - 1.0))
    assert not bad, "live curves understate: " + ", ".join(bad[:4])
    return "fixture and {} live curves match the reference integral".format(
        sum(len(v) for v in c.event_perils.values()))


@invariant("INT-STEP", "integration",
           "a flood defence is a discontinuity, not a ramp")
def _(c):
    from app import protection as prot
    from app.engine import loss_curve
    worst, worst_id = 0.0, ""
    for a in c.assets:
        for r in c.event_perils[a.id]:
            p = prot.sop(a.lon, a.lat, r.peril)
            if not p:
                continue
            rr, ii = with_step_knot(r.reading.return_periods, r.reading.intensities, p)
            if len(rr) == len(r.reading.return_periods):
                continue
            ref = loss_curve(rr, ii, r.curve["x"], r.curve["y"], a.value,
                             r.curve.get("calibration_range"), p).eal
            if ref > 0:
                err = abs(r.lc.eal - ref) / ref
                if err > worst:
                    worst, worst_id = err, "{}/{} {:,.0f} vs {:,.0f}".format(
                        a.id, r.peril, r.lc.eal, ref)
    assert worst <= 0.02, (
        "worst defended curve is {:.1%} off the knotted reference: {}. The "
        "trapezoid spanning the standard carries half a step of held-back loss"
        .format(worst, worst_id))
    return "every defended curve within 2% of its knotted reference"


def _refined_peril_eal(c, a, r, factor):
    from app import protection as prot
    from app.engine import loss_curve
    rr, ii = refine(r.reading.return_periods, r.reading.intensities, factor)
    return loss_curve(rr, ii, r.curve["x"], r.curve["y"], a.value,
                      r.curve.get("calibration_range"),
                      prot.sop(a.lon, a.lat, r.peril)).eal


@invariant("INT-CONVERGE-PF", "integration",
           "portfolio loss is converged on the modelled grid")
def _(c):
    coarse = sum(c.eal_of(a.id) for a in c.assets)
    fine = sum(_refined_peril_eal(c, a, r, 32)
               for a in c.assets for r in c.event_perils[a.id])
    assert coarse > 0, "portfolio EAL is zero"
    drift = fine / coarse - 1.0
    assert abs(drift) <= 0.02, (
        "refining the return-period grid 32x moves portfolio EAL {:+.2%} "
        "({:,.0f} to {:,.0f}); the 9-point trapezoid is not converged"
        .format(drift, coarse, fine))
    return "portfolio EAL moves {:+.2%} under 32x refinement".format(drift)


@invariant("INT-CONVERGE-PERIL", "integration",
           "every peril curve is converged on the modelled grid")
def _(c):
    bad = []
    for a in c.assets:
        for r in c.event_perils[a.id]:
            if r.lc.eal <= 0:
                continue
            fine = _refined_peril_eal(c, a, r, 32)
            drift = fine / r.lc.eal - 1.0
            if abs(drift) > 0.05:
                bad.append("{}/{} {:+.1%}".format(a.id, r.peril, drift))
    assert not bad, "{} perils move more than 5% under refinement: {}".format(
        len(bad), ", ".join(bad[:5]))
    return "no peril moves more than 5% under 32x refinement"


@invariant("INT-DECOMP", "integration", "the loss decomposition reconciles")
def _(c):
    for aid, prs in c.event_perils.items():
        for r in prs:
            lc = r.lc
            assert abs(lc.eal - (lc.eal_body + lc.eal_tail)) <= 1e-6 * max(1.0, lc.eal), (
                "{}/{}: eal != body + tail".format(aid, r.peril))
            assert lc.eal_tail >= -1e-9, "{}/{}: negative tail".format(aid, r.peril)
            assert lc.eal_tail <= lc.eal + 1e-6, (
                "{}/{}: tail exceeds total".format(aid, r.peril))
    ts = c.summ["headline"]["tail_share"]
    assert 0.0 <= ts <= 1.0, "tail_share {} outside [0,1]".format(ts)
    return "eal == body + tail on every curve; tail_share {:.1%}".format(ts)


@invariant("INT-MONO-RP", "integration", "loss is non-decreasing in return period")
def _(c):
    for aid, prs in c.event_perils.items():
        for r in prs:
            ls = r.lc.losses
            for i in range(len(ls) - 1):
                assert ls[i] <= ls[i + 1] + 1e-6, (
                    "{}/{}: loss falls from {:,.0f} to {:,.0f} between "
                    "1-in-{:g} and 1-in-{:g}".format(
                        aid, r.peril, ls[i], ls[i + 1],
                        r.lc.return_periods[i], r.lc.return_periods[i + 1]))
    return "rarer events are never cheaper, on every curve"


@invariant("INT-SCALE", "integration", "loss is exactly linear in asset value")
def _(c):
    from app.engine import loss_curve
    one = loss_curve(FIXTURE_RPS, FIXTURE_INTS, FIXTURE_X, FIXTURE_Y, 1e8).eal
    two = loss_curve(FIXTURE_RPS, FIXTURE_INTS, FIXTURE_X, FIXTURE_Y, 2e8).eal
    assert abs(two - 2 * one) <= 1e-9 * max(1.0, two), (
        "doubling asset value gave {:.12g}x, not 2x".format(two / one if one else 0))
    a, b = c.summ["headline"], c.summ_doubled["headline"]
    ratio = b["eal"] / a["eal"] if a["eal"] else 0.0
    assert abs(ratio - 2.0) <= 1e-6, (
        "doubling every asset scaled portfolio EAL by {:.9f}x".format(ratio))
    return "unit and portfolio both scale exactly 2x"


@invariant("INT-BOUNDS", "integration", "losses stay inside their physical bounds")
def _(c):
    for aid, prs in c.event_perils.items():
        a = c.by_id[aid]
        for r in prs:
            for f in r.lc.damage_fractions:
                assert -1e-12 <= f <= 1.0 + 1e-12, (
                    "{}/{}: damage fraction {:.4f} outside [0,1]".format(aid, r.peril, f))
        e = c.eal_of(aid)
        assert -1e-9 <= e <= a.value + 1e-6, (
            "{}: EAL {:,.0f} outside [0, value {:,.0f}]".format(aid, e, a.value))
    h = c.summ["headline"]
    assert 0.0 <= h["eal"] <= h["total_value"], "portfolio EAL outside [0, total value]"
    return "all damage fractions in [0,1]; all EALs inside asset value"


@invariant("INT-MONO-INTENSITY", "integration",
           "a worse hazard is never a smaller loss")
def _(c):
    from app import protection as prot
    from app.engine import loss_curve
    base = loss_curve(FIXTURE_RPS, FIXTURE_INTS, FIXTURE_X, FIXTURE_Y, FIXTURE_VALUE).eal
    up = loss_curve(FIXTURE_RPS, [i * 1.1 for i in FIXTURE_INTS],
                    FIXTURE_X, FIXTURE_Y, FIXTURE_VALUE).eal
    assert up >= base - 1e-9, "10% more intensity reduced the fixture EAL"
    for a in c.assets:
        for r in c.event_perils[a.id]:
            hotter = loss_curve(
                r.reading.return_periods, [i * 1.1 for i in r.reading.intensities],
                r.curve["x"], r.curve["y"], a.value,
                r.curve.get("calibration_range"), prot.sop(a.lon, a.lat, r.peril)).eal
            assert hotter >= r.lc.eal - 1e-6, (
                "{}/{}: 10% more intensity cut EAL from {:,.0f} to {:,.0f}"
                .format(a.id, r.peril, r.lc.eal, hotter))
    return "monotone in intensity on the fixture and every live curve"


@invariant("INT-MONO-PROTECTION", "integration",
           "a taller defence is never a larger loss")
def _(c):
    from app.engine import loss_curve
    prev, seq = None, []
    for p in (None, 5, 25, 100, 500):
        e = loss_curve(FIXTURE_RPS, FIXTURE_INTS, FIXTURE_X, FIXTURE_Y,
                       FIXTURE_VALUE, None, p).eal
        seq.append(e)
        if prev is not None:
            assert e <= prev + 1e-9, (
                "raising protection to 1-in-{} raised EAL from {:,.0f} to {:,.0f}"
                .format(p, prev, e))
        prev = e
    return "EAL falls monotonically across protection standards: " + \
        ", ".join("{:,.0f}".format(x) for x in seq)


@invariant("INT-DRY", "integration", "a dry asset costs exactly zero")
def _(c):
    from app.engine import loss_curve
    lc = loss_curve(FIXTURE_RPS, [0.0] * 9, FIXTURE_X, FIXTURE_Y, FIXTURE_VALUE)
    assert lc.eal == 0.0, "zero intensity gave EAL {!r}, not exactly 0.0".format(lc.eal)
    dry = [a for a in c.assets if not c.event_perils[a.id]]
    for a in dry:
        row = c.rows[a.id]
        assert row["eal"] == 0.0, "{} has no exposure but EAL {}".format(a.id, row["eal"])
        assert row["impairment"] == 0.0, (
            "{} has no exposure but impairment {:,.0f}".format(a.id, row["impairment"]))
    return "exact zero on the fixture and on {} unexposed assets".format(len(dry))


# --------------------------------------------------------------------------
# 2. Vulnerability coherence
# --------------------------------------------------------------------------

@invariant("VUL-OVERLAP", "vulnerability", "an asset cannot be destroyed twice")
def _(c):
    worst, where = 0.0, ""
    for a in c.assets:
        prs = c.event_perils[a.id]
        if len(prs) < 2:
            continue
        grid = sorted({r for pr in prs for r in pr.lc.return_periods})
        for rp in grid:
            tot = sum(frac_at_rp(pr, rp) for pr in prs)
            if tot > worst:
                worst, where = tot, "{} at 1-in-{:g}".format(a.id, rp)
    assert worst <= 1.0 + 1e-9, (
        "combined damage fraction reaches {:.3f} ({}): overlapping perils are "
        "summed, so the asset is destroyed {:.2f} times".format(worst, where, worst))
    return "combined damage fraction peaks at {:.3f}".format(worst)


@invariant("VUL-MDF", "vulnerability",
           "the outage driver is an annual expectation, not a peak")
def _(c):
    bad = []
    for a in c.assets:
        for r in c.event_perils[a.id]:
            if r.lc.eal <= 0:
                continue
            expected = r.lc.eal / a.value if a.value else 0.0
            got = r.mean_damage_fraction
            if abs(got - expected) > 1e-9 * max(1e-12, expected):
                bad.append("{}/{} {:.4f} vs {:.6f}".format(a.id, r.peril, got, expected))
    assert not bad, (
        "{} peril results disagree with their own docstring (it claims the EAL "
        "as a share of value): {}".format(len(bad), ", ".join(bad[:4])))
    return "mean damage fraction equals EAL / value on every curve"


@invariant("VUL-BI", "vulnerability",
           "a loss-making asset has non-zero business interruption")
def _(c):
    from app.finance import translate
    for a in c.assets:
        e = c.eal_of(a.id)
        if e <= 0 or a.annual_revenue <= 0:
            continue
        mdf = max((r.mean_damage_fraction for r in c.event_perils[a.id]), default=0.0)
        f = translate(e, mdf, c.fin_for(a), c.assumptions)
        assert f.annual_business_interruption > 0, (
            "{} loses {:,.0f} a year but reports zero business interruption"
            .format(a.id, e))
        days = min(365.0, mdf * c.assumptions.downtime_days_per_damage_unit)
        assert 0 < days <= 365, "{}: downtime {:.1f} days outside (0, 365]".format(a.id, days)
    return "every exposed revenue-earning asset has positive outage cost"


@invariant("VUL-EXTRAP", "vulnerability", "damage never exceeds the curve it came from")
def _(c):
    from app.engine import interp_damage
    for a in c.assets:
        for r in c.event_perils[a.id]:
            top = max(r.curve["y"])
            for f in r.lc.damage_fractions:
                assert f <= top + 1e-12, (
                    "{}/{}: damage {:.4f} exceeds the curve ceiling {:.4f}"
                    .format(a.id, r.peril, f, top))
            far = interp_damage(max(r.curve["x"]) * 10, r.curve["x"], r.curve["y"])
            assert abs(far - r.curve["y"][-1]) <= 1e-12, (
                "{}/{}: curve extrapolates above its last knot".format(a.id, r.peril))
    return "damage is held flat above the last knot, never extrapolated"


# --------------------------------------------------------------------------
# 3. Insurance
# --------------------------------------------------------------------------

@invariant("INS-PAYS", "insurance", "a programme with recoverable events pays out")
def _(c):
    from app.finance import translate
    silent = []
    for a in c.assets:
        prs = c.event_perils[a.id]
        e = c.eal_of(a.id)
        if e <= 0:
            continue
        worst_event = max((max(r.lc.losses) for r in prs if r.lc.losses), default=0.0)
        if worst_event <= INS["deductible_fraction"] * a.value:
            continue
        mdf = max((r.mean_damage_fraction for r in prs), default=0.0)
        f = translate(e, mdf, c.fin_for(a), c.assumptions)
        if f.annual_insurance_recovery <= 0:
            silent.append("{} (worst event {:,.0f} > deductible {:,.0f}, premium {:,.0f})"
                          .format(a.id, worst_event,
                                  INS["deductible_fraction"] * a.value, f.annual_premium))
    assert not silent, (
        "{} assets have recoverable events yet recover nothing while still "
        "paying premium: {}. A per-event deductible is being subtracted from "
        "an annual expectation".format(len(silent), "; ".join(silent[:3])))
    return "every asset with recoverable events receives a recovery"


@invariant("INS-BOUNDED", "insurance", "recovery cannot exceed the loss or the cover")
def _(c):
    from app.finance import translate
    cap_f = INS["limit_fraction"] * (1.0 - INS["coinsurance"])
    for a in c.assets:
        e = c.eal_of(a.id)
        if e <= 0:
            continue
        mdf = max((r.mean_damage_fraction for r in c.event_perils[a.id]), default=0.0)
        f = translate(e, mdf, c.fin_for(a), c.assumptions)
        rec = f.annual_insurance_recovery
        assert rec >= -1e-9, "{}: negative recovery".format(a.id)
        assert rec <= e + 1e-6, (
            "{}: recovery {:,.0f} exceeds expected annual loss {:,.0f}".format(a.id, rec, e))
        assert rec <= cap_f * a.value + 1e-6, (
            "{}: recovery {:,.0f} exceeds the cover cap {:,.0f}"
            .format(a.id, rec, cap_f * a.value))
    return "recovery bounded by both the loss and the programme limit"


@invariant("INS-MONO-DED", "insurance", "a higher deductible never recovers more")
def _(c):
    from app.finance import Assumptions, translate
    a = max(c.assets, key=lambda x: c.eal_of(x.id))
    e = c.eal_of(a.id)
    assert e > 0, "no asset carries a loss to insure"
    mdf = max((r.mean_damage_fraction for r in c.event_perils[a.id]), default=0.0)
    prev, seq = None, []
    for d in (0.0, 0.005, 0.02, 0.05, 0.2, 0.6):
        opts = dict(INS)
        opts["deductible_fraction"] = d
        f = translate(e, mdf, c.fin_for(a), Assumptions(**opts))
        seq.append(f.annual_insurance_recovery)
        if prev is not None:
            assert f.annual_insurance_recovery <= prev + 1e-6, (
                "raising the deductible to {:.1%} raised recovery".format(d))
        prev = f.annual_insurance_recovery
    return "recovery falls monotonically as the deductible rises"


@invariant("INS-RECONCILE", "insurance", "the insurance headline reconciles")
def _(c):
    h = c.summ["headline"]
    ins, ret = h["insured_share"], h["retained_share"]
    assert abs(ins + ret - 1.0) <= 1e-4, (
        "insured {:.4f} + retained {:.4f} != 1".format(ins, ret))
    assert ins <= 1.0 + 1e-9, "insured share above 1: the clamp is doing real work"
    gap, eal = h["protection_gap"], h["eal"]
    assert abs(gap - eal * (1.0 - ins)) <= max(1.0, 1e-4 * eal), (
        "protection gap {:,.0f} does not equal EAL x retained share {:,.0f}"
        .format(gap, eal * (1.0 - ins)))
    return "insured {:.1%}, retained {:.1%}, gap reconciles".format(ins, ret)


# --------------------------------------------------------------------------
# 4. Determinism and provenance
# --------------------------------------------------------------------------

def _strip(d):
    out = json.loads(json.dumps(d))
    out["provenance"].pop("computed_at", None)
    for row in out.get("yearly", []):
        row.pop("year", None)
    for row in out.get("impairment_path", []):
        row.pop("year", None)
    return out


@invariant("DET-REPEAT", "determinism", "the same inputs give the same answer")
def _(c):
    assert _strip(c.summ) == _strip(c.summ_repeat), (
        "two identical runs produced different output")
    assert c.summ["provenance"]["run_id"] == c.summ_repeat["provenance"]["run_id"], (
        "run id is not stable across identical runs")
    return "byte-identical across two runs"


@invariant("DET-ORDER", "determinism", "asset order cannot change the answer")
def _(c):
    a, b = c.summ["headline"], c.summ_reversed["headline"]
    assert a == b, "reversing the portfolio changed the headline"
    ra = sorted(c.summ["assets"], key=lambda r: r["id"])
    rb = sorted(c.summ_reversed["assets"], key=lambda r: r["id"])
    assert ra == rb, "reversing the portfolio changed the asset rows"
    return "headline and rows identical under reversal"


@invariant("DET-RUNID", "determinism", "the run id is a function of its inputs")
def _(c):
    before = c.summ["provenance"]["run_id"]
    after = c.summ_mutated["provenance"]["run_id"]
    assert before != after, (
        "changing an asset's value from {:,.0f} to 1 left the run id at {}. A "
        "provenance id that does not move when the portfolio moves is not a "
        "provenance id".format(c.assets[0].value, before))
    return "run id moves when the portfolio moves"


@invariant("DET-SCENARIO", "determinism", "a hotter scenario is never cheaper")
def _(c):
    bad = []
    r126 = {r["id"]: r["eal"] for r in c.summ_126["assets"]}
    r245 = {r["id"]: r["eal"] for r in c.summ_245["assets"]}
    r585 = {r["id"]: r["eal"] for r in c.summ["assets"]}
    for aid in r585:
        hot, mid, cool = r585[aid], r245.get(aid, 0.0), r126.get(aid, 0.0)
        if hot < mid - 1e-6 or mid < cool - 1e-6:
            bad.append("{} 126={:,.0f} 245={:,.0f} 585={:,.0f}".format(
                aid, cool, mid, hot))
    assert not bad, "scenario ordering violated: " + ", ".join(bad[:3])
    h126 = c.summ_126["headline"]["eal"]
    h585 = c.summ["headline"]["eal"]
    assert h585 >= h126 - 1e-6, "ssp585 portfolio is cheaper than ssp126"
    return "ssp585 >= ssp245 >= ssp126 on every asset and at portfolio level"


# --------------------------------------------------------------------------
# 5. Portfolio coherence
# --------------------------------------------------------------------------

@invariant("AGG-SUM", "coherence", "the whole equals the sum of its parts")
def _(c):
    h = c.summ["headline"]
    rows = c.summ["assets"]
    tot = sum(r["eal"] for r in rows)
    assert abs(tot - h["eal"]) <= max(1.0, 1e-6 * h["eal"]), (
        "headline EAL {:,.0f} != sum of rows {:,.0f}".format(h["eal"], tot))
    shares = sum(p["share"] for p in c.summ["perils"])
    assert abs(shares - 1.0) <= 1e-3, "peril shares sum to {:.4f}".format(shares)
    assert sum(h["bands"].values()) == h["asset_count"], "bands do not cover every asset"
    return "rows, peril shares and bands all reconcile"


@invariant("AGG-IN-SWEEP", "coherence", "the headline is a member of its own sweep")
def _(c):
    h = c.summ["headline"]
    sp = h["eal_spread"]
    assert sp["low"] <= h["eal"] <= sp["high"], (
        "headline {:,.0f} outside its spread {:,.0f}-{:,.0f}"
        .format(h["eal"], sp["low"], sp["high"]))
    assert c.sweep, "the sweep produced no values"
    closest = min(c.sweep, key=lambda v: abs(v - h["eal"]))
    rel = abs(closest - h["eal"]) / h["eal"] if h["eal"] else 0.0
    assert rel <= 1e-6, (
        "no sweep point matches the headline; nearest is {:,.0f} vs {:,.0f} "
        "({:.2%} off): the sweep and the headline are different models"
        .format(closest, h["eal"], rel))
    return "headline matches a sweep point exactly and sits inside the range"


@invariant("SWEEP-DISTINCT", "coherence", "every sweep point is a distinct model")
def _(c):
    n = len(c.sweep)
    distinct = len({sig(v) for v in c.sweep})
    assert distinct == n, (
        "{} sweep points carry only {} distinct values: duplicated model "
        "configurations are biasing the median and inflating n"
        .format(n, distinct))
    return "{} sweep points, all distinct".format(n)


@invariant("SWEEP-NONDEGEN", "coherence", "real disagreement survives the sweep")
def _(c):
    sp = c.summ["headline"]["eal_spread"]
    assert sp["n"] >= MIN_SWEEP_POINTS, (
        "sweep collapsed to {} points, below the {} floor".format(sp["n"], MIN_SWEEP_POINTS))
    ratio = sp["high"] / sp["low"] if sp["low"] > 0 else 0.0
    assert ratio >= MIN_SWEEP_RANGE_RATIO, (
        "high/low is {:.2f}, below the {:.1f} floor: the models no longer disagree"
        .format(ratio, MIN_SWEEP_RANGE_RATIO))
    return "n={}, high/low {:.2f}".format(sp["n"], ratio)


@invariant("BAND-CONSISTENT", "coherence", "risk bands match the numbers they label")
def _(c):
    for r in c.summ["assets"]:
        want = c.compute.band_for(r["eal_pct"])
        assert r["band"] == want, (
            "{}: banded {} at {:.4%}, should be {}".format(
                r["id"], r["band"], r["eal_pct"], want))
    occupied = sum(1 for v in c.summ["headline"]["bands"].values() if v)
    assert occupied >= 2, "every asset landed in one band; the banding is not discriminating"
    return "{} bands occupied, every row correctly labelled".format(occupied)


@invariant("COV-ATTRIBUTABLE", "coherence", "a reported breach is caused by climate")
def _(c):
    from app.finance import translate
    preexisting = []
    for r in c.summ["assets"]:
        if not r["covenant_breach"]:
            continue
        a = c.by_id[r["id"]]
        base = translate(0.0, 0.0, c.fin_for(a), c.assumptions)
        if base.covenant_breach:
            preexisting.append("{} (dscr_before {:.2f}, ltv_before {:.2f})"
                               .format(a.id, base.dscr_before, base.ltv_before))
    assert not preexisting, (
        "{} of {} reported breaches already breach at zero climate loss: {}"
        .format(len(preexisting), c.summ["headline"]["covenant_breaches"],
                "; ".join(preexisting[:3])))
    return "every reported breach is climate-attributable"


@invariant("FIN-ZERO", "coherence", "no hazard means no financial effect")
def _(c):
    from app.finance import translate
    for a in c.assets:
        f = translate(0.0, 0.0, c.fin_for(a), c.assumptions)
        assert f.annual_physical_damage == 0.0, "{}: damage at zero hazard".format(a.id)
        assert f.annual_business_interruption == 0.0, "{}: BI at zero hazard".format(a.id)
        assert f.npv_climate_cost == 0.0, (
            "{}: NPV {:,.2f} at zero hazard".format(a.id, f.npv_climate_cost))
        assert f.value_impairment == 0.0, "{}: impairment at zero hazard".format(a.id)
        assert f.ltv_after == f.ltv_before, "{}: LTV moved at zero hazard".format(a.id)
        assert f.value_impairment <= a.value, "{}: impairment exceeds value".format(a.id)
    return "zero hazard produces zero cost, zero impairment and no LTV movement"


# --------------------------------------------------------------------------
# 6. Anti-degeneracy anchors
#
# These exist so the invariants above cannot be satisfied by deleting the
# model. A zeroed engine passes every bound and fails all five of these.
# --------------------------------------------------------------------------

@invariant("PLAUS-PORTFOLIO", "anchors", "portfolio loss is physically plausible")
def _(c):
    pct = c.summ["headline"]["eal_pct_of_value"]
    lo, hi = PLAUSIBLE_EAL_PCT
    assert lo <= pct <= hi, (
        "portfolio EAL is {:.4%} of value a year, outside the plausible band "
        "{:.2%}-{:.2%}".format(pct, lo, hi))
    return "portfolio EAL {:.4%} of value".format(pct)


@invariant("PLAUS-MEDIAN", "anchors", "the median asset is not a write-off")
def _(c):
    pcts = sorted(r["eal_pct"] for r in c.summ["assets"])
    n = len(pcts)
    med = pcts[n // 2] if n % 2 else 0.5 * (pcts[n // 2 - 1] + pcts[n // 2])
    assert med <= PLAUSIBLE_MEDIAN_ASSET_EAL_PCT, (
        "the median asset loses {:.2%} a year, above the {:.0%} ceiling"
        .format(med, PLAUSIBLE_MEDIAN_ASSET_EAL_PCT))
    return "median asset loses {:.4%} a year".format(med)


@invariant("PLAUS-CONCENTRATION", "anchors", "losses are not universal")
def _(c):
    rows = c.summ["assets"]
    heavy = [r["id"] for r in rows if r["eal_pct"] > 0.05]
    assert len(heavy) <= MAX_SHARE_OF_ASSETS_ABOVE_5PCT * len(rows), (
        "{} of {} assets lose over 5% of value a year ({})"
        .format(len(heavy), len(rows), ", ".join(heavy)))
    return "{} of {} assets above 5% of value".format(len(heavy), len(rows))


@invariant("PLAUS-COVERAGE", "anchors", "the model is still modelling something")
def _(c):
    h = c.summ["headline"]
    with_loss = [r["id"] for r in c.summ["assets"] if r["eal"] > 0]
    assert len(with_loss) >= MIN_ASSETS_WITH_LOSS, (
        "only {} assets carry any loss, below the floor of {}"
        .format(len(with_loss), MIN_ASSETS_WITH_LOSS))
    assert len(c.summ["perils"]) >= MIN_PERILS_IN_ATTRIBUTION, (
        "only {} perils appear in the attribution".format(len(c.summ["perils"])))
    assert h["npv_climate_cost"] > 0, "portfolio NPV collapsed to zero"
    assert h["value_impairment"] > 0, "portfolio impairment collapsed to zero"
    return "{} assets with loss across {} perils".format(len(with_loss), len(c.summ["perils"]))


@invariant("API-SHAPE", "anchors", "the public surface is unchanged")
def _(c):
    from app import compute, engine
    from app.finance import Assumptions, appraise, translate
    want = {
        "engine.loss_curve": ["return_periods", "intensities", "curve_x", "curve_y",
                              "asset_value", "calibration_range", "protection_rp"],
        "engine.spread": ["values", "drivers"],
        "finance.translate": ["eal", "mean_damage_fraction", "fin", "a"],
        "compute.summary": ["scenario", "overrides"],
        "compute.asset_detail": ["asset_id", "scenario", "overrides"],
    }
    got = {
        "engine.loss_curve": list(inspect.signature(engine.loss_curve).parameters),
        "engine.spread": list(inspect.signature(engine.spread).parameters),
        "finance.translate": list(inspect.signature(translate).parameters),
        "compute.summary": list(inspect.signature(compute.summary).parameters),
        "compute.asset_detail": list(inspect.signature(compute.asset_detail).parameters),
    }
    for k in want:
        assert got[k] == want[k], "{} signature changed: {} != {}".format(k, got[k], want[k])
    fields = set(Assumptions().__dataclass_fields__)
    for k in INS:
        assert k in fields, "Assumptions lost the field {}".format(k)
    return "five entry points and the Assumptions field set unchanged"


# --------------------------------------------------------------------------
# Harness
# --------------------------------------------------------------------------

def git(*args):
    try:
        return subprocess.run(["git"] + list(args), capture_output=True, text=True,
                              cwd=os.path.dirname(os.path.abspath(__file__)),
                              timeout=15).stdout.strip()
    except Exception:
        return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--experiment", type=int, default=None)
    args = ap.parse_args()

    t0 = time.time()
    here = os.path.abspath(__file__)
    result = {
        "schema": 1,
        "experiment": args.experiment,
        "git_sha": git("rev-parse", "HEAD"),
        "git_subject": git("log", "-1", "--format=%s"),
        "eval_sha256": hashlib.sha256(open(here, "rb").read()).hexdigest()[:16],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    try:
        ctx = Ctx()
    except Exception as e:
        result.update({
            "score": 0, "total": len(_REG), "checks": [],
            "duration_s": round(time.time() - t0, 2),
            "aborted": "{}: {}".format(type(e).__name__, e)[:400],
        })
        print(json.dumps(result, indent=2))
        return

    checks = []
    for inv_id, group, name, fn in _REG:
        t = time.time()
        try:
            detail, held = (fn(ctx) or ""), True
        except AssertionError as e:
            detail, held = str(e), False
        except Exception as e:
            detail, held = "ERROR: {}: {}".format(type(e).__name__, e), False
        checks.append({
            "name": inv_id, "group": group, "title": name, "held": held,
            "detail": detail[:400],
            "duration_ms": round((time.time() - t) * 1000, 1),
        })

    h = ctx.summ["headline"]
    by_group = {}
    for ch in checks:
        g = by_group.setdefault(ch["group"], [0, 0])
        g[1] += 1
        if ch["held"]:
            g[0] += 1

    result.update({
        "score": sum(1 for ch in checks if ch["held"]),
        "total": len(checks),
        "duration_s": round(time.time() - t0, 2),
        "aborted": None,
        "by_group": by_group,
        "headline": {
            "eal": h["eal"],
            "eal_pct_of_value": h["eal_pct_of_value"],
            "npv_climate_cost": h["npv_climate_cost"],
            "insured_share": h["insured_share"],
            "spread_n": h["eal_spread"]["n"],
            "covenant_breaches": h["covenant_breaches"],
        },
        "checks": checks,
    })
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
