#!/usr/bin/env python3
"""Build data/damage_curves.json: citable depth-damage and wind-damage functions.

Sources (all public, no credentials):

  1. JRC global flood depth-damage functions -- Huizinga, De Moel & Szewczyk (2017),
     "Global flood depth-damage functions: Methodology and the database with guidelines",
     EUR 28552 EN, JRC105688, doi:10.2760/16510.
     - Residential / Commercial / Industrial continental curves are read from the copy
       physrisk-lib ships (`EU JRC global flood depth-damage functions.json`), which
       carries more significant figures than the rounded tables in the report PDF. Every
       such curve is cross-checked at build time against report Tables 3-1..3-13; where
       the two disagree beyond rounding the published table wins and the disagreement is
       recorded in the output's `source_discrepancies` (North America / Industrial
       currently disagrees by up to 0.03).
     - Transport / Infrastructure / Agriculture curves are transcribed literals from the
       report tables (physrisk does not ship them). Table number is on every curve.

  2. HAZUS 6.1 damage functions from the public OS-Climate S3 bucket.
     - Flood: HazusFloodDamageFunctions_Hazus61.xlsx (building structure + contents),
       and flUtilFltyDmgFn.csv (utility facilities). Downloaded by this script.
     - Wind: taken from physrisk-lib's `vulnerability_config.csv`, which is generated by
       physrisk's own ConfigBuilderHazusWind from HazusWindDamFunctions_Hazus61.xlsx
       (huDamLossFun, averaged over the 5 terrain classes, mph converted to m/s). Reused
       rather than re-derived; the 102 MB source workbook is therefore not downloaded.

  3. Eberenz, Luethi & Bresch (2021), "Regional tropical cyclone impact functions for
     globally consistent risk assessments", NHESS 21(1):393-415 -- regional TC wind
     curves, via physrisk-lib's vulnerability_config.csv.

  4. Offshore wind turbine wind fragility, via physrisk-lib's vulnerability_config.csv
     (NREL/TP-5000-80639 and Rose et al. 2012, PNAS 109(9):3243-3248).

Run:  python data/build_curves.py         # build + self-check
      python data/build_curves.py --check # self-check the existing JSON only
"""

from __future__ import annotations

import ast
import csv
import datetime as dt
import json
import sys
import urllib.request
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent
SOURCE_DIR = DATA_DIR / "_sources"
OUT = DATA_DIR / "damage_curves.json"

S3 = "https://os-climate-physical-risk.s3.us-east-1.amazonaws.com/vulnerability/"
DOWNLOADS = {
    "HazusFloodDamageFunctions_Hazus61.xlsx": S3 + "HazusFloodDamageFunctions_Hazus61.xlsx",
    "flUtilFltyDmgFn.csv": S3 + "flUtilFltyDmgFn.csv",
}

JRC_DOI = "Huizinga, De Moel & Szewczyk (2017), EUR 28552 EN / JRC105688, doi:10.2760/16510"
JRC_PDF = (
    "https://publications.jrc.ec.europa.eu/repository/bitstream/JRC105688/"
    "global_flood_depth-damage_functions__10042017.pdf"
)
JRC_WB = "https://datacatalog.worldbank.org/search/dataset/0065170/Global-flood-depth-damage-functions"

FT_TO_M = 0.3048

# Continents for which the JRC report had enough underlying damage functions to call the
# continental average well-supported (report sections 3.1-3.2). Everything else is a
# thinner average and is marked down. See "confidence_basis" in the output.
JRC_WELL_SUPPORTED = {"Europe", "North America", "Asia"}


# --------------------------------------------------------------------------------------
# 1. JRC flood -- Residential / Commercial / Industrial, from physrisk-lib's shipped copy
# --------------------------------------------------------------------------------------

# report table numbers for the continental building curves, for citation
JRC_BUILDING_TABLES = {
    ("Residential", "Africa"): "Table 3-1",
    ("Residential", "Asia"): "Table 3-2",
    ("Residential", "Oceania"): "Table 3-3",
    ("Residential", "North America"): "Table 3-4",
    ("Residential", "South America"): "Table 3-5",
    ("Residential", "Europe"): "section 3.1 (European reference curve)",
    ("Commercial", "Asia"): "Table 3-6",
    ("Commercial", "Oceania"): "Table 3-7",
    ("Commercial", "North America"): "Table 3-8",
    ("Commercial", "South America"): "Table 3-9",
    ("Commercial", "Africa"): "section 3.2.2 (Europe used as proxy, no African data)",
    ("Commercial", "Europe"): "section 3.2.2 (European reference curve)",
    ("Industrial", "Africa"): "Table 3-10",
    ("Industrial", "Asia"): "Table 3-11",
    ("Industrial", "North America"): "Table 3-12",
    ("Industrial", "South America"): "Table 3-13",
    ("Industrial", "Oceania"): "section 3.2.3 (Europe used as proxy, no Oceanian data)",
    ("Industrial", "Europe"): "section 3.2.3 (European reference curve)",
}


# The published report tables, transcribed at the depths in JRC_DEPTHS. physrisk's
# shipped copy carries more significant figures, so we prefer it -- but only where the two
# actually agree. Any real disagreement is resolved in favour of the citable report table
# and recorded in the output's "source_discrepancies". Europe and Global have no such
# table (Europe is the reference curve, Global is an average) and are not cross-checked.
JRC_REPORT_TABLES = {
    ("Residential", "Africa"): [0, 0.22, 0.38, 0.53, 0.64, 0.82, 0.90, 0.96, 1.00],
    ("Residential", "Asia"): [0, 0.33, 0.49, 0.62, 0.72, 0.87, 0.93, 0.98, 1.00],
    ("Residential", "Oceania"): [0.04, 0.48, 0.64, 0.71, 0.79, 0.93, 0.97, 0.98, 1.00],
    ("Residential", "North America"): [0.20, 0.44, 0.58, 0.68, 0.78, 0.85, 0.92, 0.96, 1.00],
    ("Residential", "South America"): [0, 0.49, 0.71, 0.84, 0.95, 0.98, 1.00, 1.00, 1.00],
    ("Commercial", "Asia"): [0, 0.38, 0.54, 0.66, 0.76, 0.88, 0.94, 0.98, 1.00],
    ("Commercial", "Oceania"): [0, 0.24, 0.48, 0.67, 0.86, 1.00, 1.00, 1.00, 1.00],
    ("Commercial", "North America"): [0.02, 0.24, 0.37, 0.47, 0.55, 0.69, 0.82, 0.91, 1.00],
    ("Commercial", "South America"): [0, 0.61, 0.84, 0.92, 0.99, 1.00, 1.00, 1.00, 1.00],
    ("Industrial", "Africa"): [0, 0.06, 0.25, 0.40, 0.49, 0.68, 0.92, 1.00, 1.00],
    ("Industrial", "Asia"): [0, 0.28, 0.48, 0.63, 0.72, 0.86, 0.91, 0.96, 1.00],
    ("Industrial", "North America"): [0.02, 0.31, 0.48, 0.61, 0.71, 0.84, 0.93, 0.98, 1.00],
    ("Industrial", "South America"): [0, 0.67, 0.89, 0.95, 1.00, 1.00, 1.00, 1.00, 1.00],
}

# collected during build(), surfaced at the top level of the JSON
DISCREPANCIES: list[dict] = []


def _reconcile_with_report(occ: str, region: str, x: list, y: list) -> tuple[list, list, bool]:
    """Compare a physrisk curve against the published table; report table wins.

    physrisk represents the report's damage value at zero depth by placing 0.0 at 0 m and
    the published value at 0.01 m, so the depth-0 row is compared against whichever of
    those two points carries the value.
    """
    table = JRC_REPORT_TABLES.get((occ, region))
    if table is None:
        return x, y, False

    lookup = dict(zip(x, y))
    diffs = []
    for depth, published in zip(JRC_DEPTHS, table):
        got = lookup.get(0.01, lookup.get(0.0)) if depth == 0 else lookup.get(float(depth))
        if got is None:
            continue
        if abs(round(got, 2) - published) > 0.005:
            diffs.append({"depth_m": depth, "physrisk": round(got, 4), "report": published})

    if not diffs:
        return x, y, False

    curve_id = f"jrc_flood_{slug(region)}_{slug(occ)}"

    if len(diffs) == 1 and diffs[0]["depth_m"] == 0:
        # Only the zero-depth value differs: physrisk simply omitted it. Reinstate it at
        # 0.01 m, which is the convention physrisk itself uses for the other continents,
        # and keep physrisk's extra significant figures everywhere else.
        DISCREPANCIES.append(
            {
                "curve_id": curve_id,
                "issue": (
                    "physrisk-lib dropped the report's non-zero damage value at zero "
                    "depth; the rest of the curve agrees."
                ),
                "points": diffs,
                "resolution": (
                    "report value reinstated at 0.01 m, matching physrisk's own "
                    "convention on other continents; remaining points unchanged"
                ),
            }
        )
        merged = sorted(zip(x, y) if 0.01 in x else list(zip(x, y)) + [(0.01, table[0])])
        return [p[0] for p in merged], [p[1] for p in merged], False

    DISCREPANCIES.append(
        {
            "curve_id": curve_id,
            "issue": (
                "physrisk-lib's bundled JRC values disagree with the published report "
                "table beyond rounding. Resolved in favour of the report, which is what "
                "the curve cites."
            ),
            "points": diffs,
            "resolution": "report table values used; confidence downgraded to medium",
        }
    )
    return list(JRC_DEPTHS), list(table), True


def physrisk_dir() -> Path:
    import physrisk  # noqa: F401  (import for its location only)

    return Path(physrisk.__file__).resolve().parent / "data" / "static" / "vulnerability"


def jrc_building_curves() -> list[dict]:
    src = physrisk_dir() / "EU JRC global flood depth-damage functions.json"
    items = json.loads(src.read_text())["items"]
    out = []
    for it in items:
        occ = it["asset_type"].split("/")[-1]  # Buildings/Residential -> Residential
        region = it["location"]
        if not it["impact_mean"]:
            # physrisk leaves three entries blank: Africa/Commercial and
            # Oceania/Industrial (the JRC report found no data for either and tells the
            # reader to substitute the European curve) and Global/Residential (no such
            # curve in the report). Handled explicitly below rather than filled in here.
            continue
        table = JRC_BUILDING_TABLES.get((occ, region), "continental average, section 3.2")
        x = [round(v, 4) for v in it["intensity"]]
        y = [round(v, 4) for v in it["impact_mean"]]
        conf = "high" if region in JRC_WELL_SUPPORTED else "medium"
        if region == "Global":
            conf = "medium"

        x, y, overridden = _reconcile_with_report(occ, region, x, y)
        note = (
            "values as shipped in physrisk-lib "
            "'EU JRC global flood depth-damage functions.json'; "
            "verified against the report table to 2 d.p."
        )
        if overridden:
            conf = "medium"
            note = (
                "physrisk-lib's bundled values disagreed with the published report table "
                "beyond rounding, so the report table is used here. See "
                "source_discrepancies at the top level of this file."
            )
        out.append(
            {
                "id": f"jrc_flood_{slug(region)}_{slug(occ)}",
                "hazard": "flood",
                "sub_hazard": "riverine_inundation",
                "region": region,
                "occupancy": occ,
                "damage_basis": "structure",
                "x_units": "m_inundation_depth",
                "x": x,
                "y": y,
                "source": f"{JRC_DOI}, {table}",
                "source_note": note,
                "confidence": conf,
                "calibration_range": [min(x), max(x)],
            }
        )
    out += _jrc_europe_proxies(out)
    return out


# The JRC report has no Commercial data for Africa and no Industrial data for Oceania,
# and instructs the reader to fall back on the European curve (sections 3.2.2, 3.2.3).
# Emitted so the six-continent grid is complete, but loudly flagged: same numbers as
# Europe, confidence low, proxy_for set. Not a separate empirical curve.
JRC_EUROPE_PROXY = [("Africa", "Commercial"), ("Oceania", "Industrial")]


def _jrc_europe_proxies(built: list[dict]) -> list[dict]:
    by_key = {(c["region"], c["occupancy"]): c for c in built}
    out = []
    for region, occ in JRC_EUROPE_PROXY:
        base = by_key[("Europe", occ)]
        c = dict(base)
        c["id"] = f"jrc_flood_{slug(region)}_{slug(occ)}"
        c["region"] = region
        c["confidence"] = "low"
        c["proxy_for"] = "Europe"
        c["source"] = (
            f"{JRC_DOI}: European {occ} curve applied to {region} as the report "
            f"directs, no {region} {occ} data existed"
        )
        c["source_note"] = (
            f"NOT an empirical {region} curve. Identical values to "
            f"jrc_flood_europe_{slug(occ)}. Use only as a placeholder and expect the "
            f"error to be large."
        )
        out.append(c)
    return out


# --------------------------------------------------------------------------------------
# 2. JRC flood -- Transport / Infrastructure / Agriculture, transcribed from the report
# --------------------------------------------------------------------------------------

JRC_DEPTHS = [0, 0.5, 1, 1.5, 2, 3, 4, 5, 6]

# (region, occupancy, table, damage factors at JRC_DEPTHS, confidence)
JRC_OTHER = [
    ("Asia", "Transport", "Table 3-14",
     [0, 0.36, 0.57, 0.73, 0.85, 1.00, 1.00, 1.00, 1.00], "medium"),
    ("South America", "Transport", "Table 3-15",
     [0, 0.09, 0.18, 0.60, 0.84, 1.00, 1.00, 1.00, 1.00], "low"),
    ("Asia", "Infrastructure", "Table 3-16",
     [0, 0.25, 0.42, 0.55, 0.65, 0.80, 0.90, 1.00, 1.00], "medium"),
    ("Africa", "Agriculture", "Table 3-18",
     [0, 0.24, 0.47, 0.74, 0.92, 1.00, 1.00, 1.00, 1.00], "medium"),
    ("Asia", "Agriculture", "Table 3-19",
     [0, 0.17, 0.37, 0.51, 0.56, 0.69, 0.83, 0.97, 1.00], "medium"),
    ("North America", "Agriculture", "Table 3-20",
     [0.02, 0.27, 0.48, 0.56, 0.61, 0.76, 0.88, 0.95, 1.00], "medium"),
    ("Global", "Agriculture", "Table 5-4",
     [0.00, 0.23, 0.39, 0.55, 0.65, 0.78, 0.87, 0.96, 1.00], "low"),
    ("Global", "Infrastructure", "Table 5-4",
     [0.00, 0.22, 0.43, 0.58, 0.67, 0.79, 0.89, 0.97, 1.00], "low"),
]


def jrc_other_curves() -> list[dict]:
    out = []
    for region, occ, table, y, conf in JRC_OTHER:
        note = (
            "generic global function, average of the available continental functions "
            "(report section 5.4); the report itself flags the underlying data as limited"
            if table == "Table 5-4"
            else "transcribed from the report table; physrisk-lib does not ship this class"
        )
        out.append(
            {
                "id": f"jrc_flood_{slug(region)}_{slug(occ)}",
                "hazard": "flood",
                "sub_hazard": "riverine_inundation",
                "region": region,
                "occupancy": occ,
                "damage_basis": "structure",
                "x_units": "m_inundation_depth",
                "x": list(JRC_DEPTHS),
                "y": list(y),
                "source": f"{JRC_DOI}, {table}",
                "source_note": note,
                "confidence": conf,
                "calibration_range": [0, 6],
            }
        )
    return out


# JRC max damage values, Euro/m2 at 2010 price level (agriculture is Euro/m2 of
# agricultural land; infrastructure/roads is Euro/m of road). "" = not reported.
JRC_MAX_DAMAGE_CONTINENT = {  # report Table 3-21
    "Africa": {"Residential": 495, "Commercial": None, "Industrial": 120,
               "Transport": None, "Infrastructure": 267, "Agriculture": 0.12},
    "Asia": {"Residential": 111, "Commercial": 138, "Industrial": 114,
             "Transport": 209, "Infrastructure": 4, "Agriculture": 0.03},
    "Oceania": {"Residential": 541, "Commercial": 506, "Industrial": None,
                "Transport": None, "Infrastructure": 7, "Agriculture": 4.85},
    "North America": {"Residential": 788, "Commercial": 1889, "Industrial": 1830,
                      "Transport": None, "Infrastructure": 39, "Agriculture": 662},
    "South America": {"Residential": 215, "Commercial": 213, "Industrial": 137,
                      "Transport": None, "Infrastructure": None, "Agriculture": None},
    "Europe": {"Residential": 750, "Commercial": 621, "Industrial": 534,
               "Transport": 751, "Infrastructure": 24, "Agriculture": 0.77},
}

JRC_MAX_DAMAGE_COUNTRY = {  # report Table 3-22, order: Res, Com, Ind, Transport, Infra, Agri
    "Mozambique": [283, None, None, None, 267, 0.1],
    "South Africa": [765, None, 120, None, None, 0.18],
    "Cambodia": [24, None, None, None, None, 0.01],
    "Bangladesh": [25, 144, 92, None, 2.5, 0.05],
    "China": [984, 1274, 1741, 414, 12, None],
    "Taiwan": [131, None, None, None, None, None],
    "India": [None, None, None, None, None, 0.01],
    "Indonesia": [6, 29, 27, 4, None, 8],
    "Thailand": [1, None, 245, None, None, 0.02],
    "Vietnam": [7, 15, None, None, 0.25, 0.1],
    "Japan": [None, 332, None, None, None, None],
    "Australia": [541, 506, None, None, 7, 4.8],
    "United States": [788, 1889, 1830, None, 39, 662],
    "Brazil": [105, 90, 29, 23, None, None],
    "St. Maarten": [326, 254, 191, None, None, None],
    "Belgium": [792, None, None, None, None, 0.55],
    "Czech Republic": [None, 130, 130, None, None, None],
    "Denmark": [259, None, None, None, None, None],
    "France": [None, 261, 257, None, None, None],
    "Germany": [526, 362, 203, None, None, None],
    "Netherlands": [717, 106, 106, 691, 60, 1.55],
    "Norway": [729, 1254, 1254, None, 14, None],
    "Switzerland": [None, None, None, None, 12, None],
    "United Kingdom": [1475, 1615, 1255, 812, 11, 0.2],
}

MAX_DAMAGE_CLASSES = ["Residential", "Commercial", "Industrial",
                      "Transport", "Infrastructure", "Agriculture"]


# --------------------------------------------------------------------------------------
# 3. HAZUS 6.1 flood -- building structure and contents (US), from the OS-Climate bucket
# --------------------------------------------------------------------------------------


def hazus_flood_curves() -> list[dict]:
    import openpyxl

    path = fetch("HazusFloodDamageFunctions_Hazus61.xlsx")
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)

    occ_cat = {}
    for r in wb["OccupancyTypes"].iter_rows(min_row=2, values_only=True):
        occ_cat[str(r[0]).strip()] = (str(r[1]).strip(), str(r[2]).strip())

    out = []
    sheets = [
        ("flBldgStrucDmgFn", "structure", "Hazus 6.1 flBldgStrucDmgFn"),
        ("flBldgContDmgFunc", "contents", "Hazus 6.1 flBldgContDmgFunc"),
    ]
    for sheet, basis, table in sheets:
        rows = list(wb[sheet].iter_rows(values_only=True))
        hdr = list(rows[0])
        i0, i1 = hdr.index("ft04m"), hdr.index("ft24") + 1
        depths_ft = [_depth_ft(h) for h in hdr[i0:i1]]
        x = [round(d * FT_TO_M, 4) for d in depths_ft]
        for r in rows[1:]:
            if str(r[1]).strip() in ("None", "", "NULL"):  # keep Hazus default functions only
                continue
            fn_id = int(r[0])
            occ = str(r[2]).strip()
            src = str(r[3]).strip()
            desc = str(r[4]).strip()
            y = [round(float(v) / 100.0, 4) for v in r[i0:i1]]
            cat, cat_desc = occ_cat.get(occ, ("Unknown", occ))
            out.append(
                {
                    "id": f"hazus_flood_{occ.lower()}_{basis}_{fn_id}",
                    "hazard": "flood",
                    "sub_hazard": "inundation",
                    "region": "North America",
                    "country": "United States",
                    "occupancy": cat,
                    "occupancy_detail": f"{occ} ({cat_desc}) - {desc}",
                    "damage_basis": basis,
                    "x_units": "m_depth_above_first_floor",
                    "x": x,
                    "y": y,
                    "source": (
                        f"FEMA Hazus 6.1 Flood Model, {table}, "
                        f"damage function id {fn_id} (originating source: {src})"
                    ),
                    "source_note": (
                        "Hazus default function. Depths are relative to the top of the "
                        "first finished floor, not ground level; negative depths apply to "
                        "basements. US-calibrated."
                    ),
                    "confidence": "high",
                    "calibration_range": [min(x), max(x)],
                }
            )
    wb.close()
    return out


def _depth_ft(col: str) -> float:
    """'ft04m' -> -4.0, 'ft00' -> 0.0, 'ft24' -> 24.0."""
    body = col[2:]
    if body.endswith("m"):
        return -float(body[:-1])
    return float(body)


def hazus_utility_flood_curves() -> list[dict]:
    path = fetch("flUtilFltyDmgFn.csv")
    x = [round(i * FT_TO_M, 4) for i in range(11)]
    out = []
    with open(path, newline="", encoding="utf-8-sig") as fh:
        for r in csv.DictReader(fh):
            occ = r["Occupancy"].strip()
            fn_id = int(r["UtilFltyDmgFnID"])
            desc = r["Description"].strip()
            desc = "" if desc in ("NULL", "") else desc
            y = [round(float(r["ft%02d" % i]) / 100.0, 4) for i in range(11)]
            out.append(
                {
                    "id": f"hazus_util_flood_{occ.lower()}_{fn_id}",
                    "hazard": "flood",
                    "sub_hazard": "inundation",
                    "region": "North America",
                    "country": "United States",
                    "occupancy": "Infrastructure",
                    "occupancy_detail": f"{occ}{' - ' + desc if desc else ''}",
                    "damage_basis": "facility",
                    "x_units": "m_depth_above_ground",
                    "x": x,
                    "y": y,
                    "source": (
                        f"FEMA Hazus 6.1, flUtilFltyDmgFn.csv, utility facility damage "
                        f"function id {fn_id} ({r['Source'].strip()})"
                    ),
                    "source_note": (
                        "Lifeline/utility facility flood damage. US-calibrated. Curve is "
                        "only tabulated to 10 ft (3.05 m); do not extrapolate."
                    ),
                    "confidence": "medium",
                    "calibration_range": [min(x), max(x)],
                }
            )
    return out


# --------------------------------------------------------------------------------------
# 4. Wind -- reused verbatim from physrisk-lib's vulnerability_config.csv
# --------------------------------------------------------------------------------------

HAZUS_WIND_SOURCE = (
    "FEMA Hazus 6.1 Hurricane Model, HazusWindDamFunctions_Hazus61.xlsx (huDamLossFun), "
    "specific building type {bt}, {dt} loss; averaged over the 5 Hazus terrain classes"
)
EBERENZ_SOURCE = (
    "Eberenz, Luethi & Bresch (2021), 'Regional tropical cyclone impact functions for "
    "globally consistent risk assessments', NHESS 21(1):393-415, Table A2 "
    "(regional v_half calibration; v_thresh = 25.7 m/s)"
)
OFFSHORE_SOURCE = (
    "Offshore wind turbine wind fragility as implemented in physrisk-lib "
    "ConfigBuilderOffshoreWind, after NREL/TP-5000-80639 and Rose, Jaramillo, Small, "
    "Grossmann & Apt (2012), PNAS 109(9):3243-3248"
)


def wind_curves() -> list[dict]:
    path = physrisk_dir() / "vulnerability_config.csv"
    out = []
    with open(path, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["hazard_class"] != "Wind":
                continue
            ident = r["asset_identifier"]
            x = [float(v) for v in ast.literal_eval(r["points_x"])]
            y = [float(v) for v in ast.literal_eval(r["points_y"])]

            if "build_type=" in ident:
                bt = ident.split("build_type=")[1].split(",")[0]
                dt = ident.split("damage_type=")[1].split(",")[0]
                if dt == "downtime":
                    # Not a damage fraction -- it is relative loss-of-use and exceeds 1.0.
                    # Recorded in "gaps" rather than silently rescaled.
                    continue
                out.append(
                    {
                        "id": f"hazus_wind_{bt.lower()}_{dt}",
                        "hazard": "wind",
                        "sub_hazard": "tropical_cyclone",
                        "region": "North America",
                        "country": "United States",
                        "occupancy": _wind_occupancy(bt),
                        "occupancy_detail": f"Hazus specific building type {bt}",
                        "damage_basis": dt,
                        "x_units": "m_s_3s_gust",
                        "x": x,
                        "y": y,
                        "source": HAZUS_WIND_SOURCE.format(bt=bt, dt=dt),
                        "source_note": (
                            "reused from physrisk-lib vulnerability_config.csv, generated "
                            "by ConfigBuilderHazusWind; original x-axis is 50-250 mph "
                            "3-second gust, converted to m/s"
                        ),
                        "confidence": "high",
                        "calibration_range": [min(x), max(x)],
                    }
                )
            elif ident.startswith("type=Generic,location="):
                loc = ident.split("location=")[1]
                out.append(
                    {
                        "id": f"eberenz_wind_tc_{slug(loc)}",
                        "hazard": "wind",
                        "sub_hazard": "tropical_cyclone",
                        "region": loc,
                        "occupancy": "Generic",
                        "damage_basis": "total_asset_value",
                        "x_units": "m_s_1min_sustained",
                        "x": x,
                        "y": y,
                        "source": EBERENZ_SOURCE,
                        "source_note": (
                            "sigmoid f = vn^3/(1+vn^3) with regional v_half; Europe and "
                            "the 'Generic' curve reuse the North Atlantic (NA2) "
                            "calibration because the paper has no separate fit for them"
                        ),
                        "confidence": "medium",
                        "calibration_range": [min(x), max(x)],
                    }
                )
            elif ident.startswith("type=Wind"):
                kind = ident.split("type=")[1]
                out.append(
                    {
                        "id": f"offshore_wind_turbine_{slug(kind)}",
                        "hazard": "wind",
                        "sub_hazard": "extreme_wind",
                        "region": "Global",
                        "occupancy": "PowerGeneratingAsset",
                        "occupancy_detail": f"wind turbine, {kind}",
                        "damage_basis": "total_asset_value",
                        "x_units": "m_s_max_speed",
                        "x": x,
                        "y": y,
                        "source": OFFSHORE_SOURCE,
                        "source_note": "reused from physrisk-lib vulnerability_config.csv",
                        "confidence": "low",
                        "calibration_range": [min(x), max(x)],
                    }
                )
    return out


_WIND_BT_PREFIX = [
    ("WSF", "Residential"), ("MSF", "Residential"), ("MH", "Residential"),
    ("WMUH", "Residential"), ("MMUH", "Residential"),
    ("CERB", "Commercial"), ("MERB", "Commercial"), ("SERB", "Commercial"),
    ("CECB", "Commercial"), ("MECB", "Commercial"), ("SECB", "Commercial"),
    ("SPMB", "Industrial"), ("MLRM", "Industrial"), ("MLRI", "Industrial"),
]


def _wind_occupancy(bt: str) -> str:
    for prefix, occ in sorted(_WIND_BT_PREFIX, key=lambda p: -len(p[0])):
        if bt.startswith(prefix):
            return occ
    return "Unknown"


# --------------------------------------------------------------------------------------
# Gaps -- hazards we deliberately did NOT fabricate a curve for
# --------------------------------------------------------------------------------------

GAPS = [
    {
        "hazard": "drought",
        "exposure": "industrial process water / manufacturing output",
        "why": (
            "No credible public depth-equivalent damage function exists. physrisk-lib "
            "ships a single generic SPEI-12 stub (points_x [-3.5,-3.0,-2.5,-2.0], "
            "points_y [1.0,0.2,0.1,0.0]) which is a decreasing 4-point placeholder with "
            "no published calibration, not a vulnerability curve. Drought loss is "
            "mediated by water rights, storage and substitution, none of which a "
            "univariate hazard-to-damage curve captures."
        ),
        "what_would_close_it": (
            "Facility-level water-withdrawal and curtailment records joined to a basin "
            "water-stress index; or a published sector water-intensity elasticity."
        ),
    },
    {
        "hazard": "wildfire",
        "exposure": "industrial and commercial sites",
        "why": (
            "No public wildfire vulnerability curve at asset-value-fraction resolution. "
            "physrisk-lib ships a single point (fire_probability 1.0 -> damage 0.7) with "
            "no source. Published wildfire fragility work is structure-specific "
            "(roof/vent/ember-defensible-space) and is not a function of a single hazard "
            "intensity variable, so it cannot be expressed in this schema honestly."
        ),
        "what_would_close_it": (
            "A burn-probability x structure-hardening matrix, e.g. from the USFS "
            "Wildfire Risk to Communities dataset plus NIST/IBHS ember-exposure testing."
        ),
    },
    {
        "hazard": "hail",
        "exposure": "buildings and solar PV",
        "why": (
            "physrisk-lib ships only two single-point stubs (days above 5 cm = 0.02 -> "
            "damage 0.001 generic, 0.3 for solar). A single point is not a curve and the "
            "underlying calibration is not published. Not included."
        ),
        "what_would_close_it": "Insurer hail claims severity vs hailstone diameter, or IEC 61215 impact test data mapped to field diameters.",
    },
    {
        "hazard": "chronic_heat",
        "exposure": "labour productivity / manufacturing",
        "why": (
            "physrisk-lib ships a WBGT-days curve for ManufacturingAsset traceable to ILO "
            "(2019) 'Working on a warmer planet'. It is a real source, but its y-axis is "
            "productivity disruption, not damage to asset value, so it does not belong in "
            "a damage-fraction dataset. Excluded on units, not on credibility."
        ),
        "what_would_close_it": "A separate disruption-curve dataset with its own units; the ILO curve can be lifted directly into it.",
    },
    {
        "hazard": "wind",
        "exposure": "loss of use / downtime",
        "why": (
            "Hazus 6.1 huDamLossFun does provide a downtime function per building type, "
            "and physrisk exposes it, but its values reach 2.22 -- it is relative "
            "loss-of-use in days, not a 0-1 damage fraction. Excluded rather than "
            "rescaled into something it is not."
        ),
        "what_would_close_it": "Include it in a downtime dataset with x_units days and no 0-1 bound.",
    },
    {
        "hazard": "flood",
        "exposure": "Transport and Infrastructure outside Asia and South America",
        "why": (
            "The JRC report found no usable damage functions for Transport in Africa, "
            "Oceania or North America, and none for Infrastructure outside Asia; it tells "
            "the user to fall back on the European curve or the generic global function. "
            "Those fallbacks are not separate empirical curves, so they are not emitted as "
            "distinct continental curves. Use jrc_flood_global_infrastructure or "
            "jrc_flood_global_agriculture, and note the substitution."
        ),
        "what_would_close_it": "Continental road/rail damage surveys; none currently public at this resolution.",
    },
    {
        "hazard": "flood",
        "exposure": "Commercial in Africa, Industrial in Oceania",
        "why": (
            "The JRC report had no underlying damage functions for either and directs the "
            "reader to substitute the European curve. jrc_flood_africa_commercial and "
            "jrc_flood_oceania_industrial are therefore copies of the European curves, "
            "marked confidence 'low' with proxy_for = 'Europe'. They are present so the "
            "six-continent grid is complete, not because the data exists."
        ),
        "what_would_close_it": "Loss data from African commercial and Oceanian industrial flood events.",
    },
    {
        "hazard": "coastal_inundation",
        "exposure": "salt-water-specific damage uplift",
        "why": (
            "The JRC and Hazus flood curves used here are freshwater/riverine. Salt water "
            "is more damaging to fabric and equipment, but no public curve quantifies the "
            "uplift globally. Applying the riverine curves to coastal flooding is a known "
            "under-estimate and is not corrected for here."
        ),
        "what_would_close_it": "Hazus coastal V-zone functions with wave action, or post-event coastal loss data.",
    },
    {
        "hazard": "wind",
        "exposure": "non-US building stock",
        "why": (
            "Every building-type wind curve here is Hazus, i.e. calibrated on US "
            "construction and US building codes. The Eberenz regional curves cover other "
            "regions but only at whole-asset generic resolution, not by building type. "
            "Do not read hazus_wind_* as valid for, say, Asian construction."
        ),
        "what_would_close_it": "Regional wind vulnerability curves, e.g. GEM/GAR or national cyclone codes.",
    },
]


# --------------------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------------------


def slug(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s.lower()).strip("_")


ROUNDING_TOLERANCE = 0.02


def enforce_monotonic(curves: list[dict]) -> None:
    """Repair dips that are clearly rounding artefacts; refuse to hide anything bigger.

    physrisk rounds its terrain-averaged Hazus wind curves to 2 d.p., which can leave a
    curve stepping down by 0.01. That is noise, not physics. A running-max clamp fixes it
    and the curve is stamped monotonic_adjusted so the edit is visible in the output. A
    dip larger than the rounding tolerance is a genuine data problem and raises.
    """
    for c in curves:
        y = c["y"]
        worst = min((b - a for a, b in zip(y, y[1:])), default=0.0)
        if worst >= -1e-9:
            continue
        if worst < -ROUNDING_TOLERANCE:
            raise ValueError(
                f"{c['id']}: y drops by {abs(worst):.3f}, too large to be rounding noise"
            )
        fixed, run = [], 0.0
        for v in y:
            run = max(run, v)
            fixed.append(round(run, 4))
        c["y"] = fixed
        c["monotonic_adjusted"] = True
        c["source_note"] = (
            c.get("source_note", "")
            + f" Running-max clamp applied: the source curve stepped down by "
            f"{abs(worst):.2f}, within rounding tolerance."
        ).strip()


def fetch(name: str) -> Path:
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    path = SOURCE_DIR / name
    if not path.exists():
        print(f"downloading {name} ...", file=sys.stderr)
        urllib.request.urlretrieve(DOWNLOADS[name], path)
    return path


def build() -> dict:
    curves = (
        jrc_building_curves()
        + jrc_other_curves()
        + hazus_flood_curves()
        + hazus_utility_flood_curves()
        + wind_curves()
    )
    curves.sort(key=lambda c: (c["hazard"], c["id"]))
    enforce_monotonic(curves)

    import physrisk

    today = dt.date.today().isoformat()
    return {
        "schema_version": "1.0",
        "generated": today,
        "generator": "data/build_curves.py",
        "provenance": {
            "jrc_flood_depth_damage": {
                "citation": (
                    "Huizinga, J., De Moel, H., Szewczyk, W. (2017). Global flood "
                    "depth-damage functions: Methodology and the database with "
                    "guidelines. EUR 28552 EN, JRC105688. doi:10.2760/16510"
                ),
                "report_pdf": JRC_PDF,
                "world_bank_data_catalogue": JRC_WB,
                "retrieved": today,
                "how_used": (
                    "Residential/Commercial/Industrial continental curves read from the "
                    "copy bundled with physrisk-lib (higher precision than the rounded "
                    "report tables, verified equal to 2 d.p.). Transport, Infrastructure "
                    "and Agriculture curves and both maximum-damage tables transcribed "
                    "from the report PDF, which physrisk-lib does not ship."
                ),
            },
            "hazus_flood": {
                "citation": "FEMA Hazus 6.1 Flood Model technical manual and database",
                "files": [
                    S3 + "HazusFloodDamageFunctions_Hazus61.xlsx",
                    S3 + "flUtilFltyDmgFn.csv",
                ],
                "retrieved": today,
                "access": "public OS-Climate S3 bucket, anonymous, no credentials",
                "how_used": (
                    "Hazus default building structure and contents functions "
                    "(Default flag set) and all utility facility functions; depths "
                    "converted ft->m, damage converted percent->fraction."
                ),
            },
            "hazus_wind": {
                "citation": "FEMA Hazus 6.1 Hurricane Model, huDamLossFun table",
                "file": S3 + "HazusWindDamFunctions_Hazus61.xlsx",
                "retrieved": today,
                "how_used": (
                    "NOT re-derived. Reused from physrisk-lib "
                    "data/static/vulnerability/vulnerability_config.csv, which "
                    "physrisk generates from this workbook via ConfigBuilderHazusWind "
                    "(average over the 5 terrain classes, mph->m/s). The source "
                    "workbook was downloaded and spot-checked to confirm this "
                    "derivation before reuse."
                ),
            },
            "eberenz_tropical_cyclone": {
                "citation": (
                    "Eberenz, S., Luethi, S., Bresch, D.N. (2021). Regional tropical "
                    "cyclone impact functions for globally consistent risk assessments. "
                    "Natural Hazards and Earth System Sciences 21(1), 393-415. "
                    "doi:10.5194/nhess-21-393-2021"
                ),
                "retrieved": today,
                "how_used": (
                    "Reused from physrisk-lib vulnerability_config.csv "
                    "(ConfigBuilderEberenzWind, Table A2 regional v_half values)."
                ),
            },
            "physrisk_lib": {
                "version": getattr(physrisk, "__version__", "unknown"),
                "path": str(physrisk_dir()),
                "retrieved": today,
            },
        },
        "confidence_basis": {
            "high": (
                "Directly published curve from a peer-reviewed or agency source, with a "
                "substantial underlying sample in the region it is applied to."
            ),
            "medium": (
                "Published curve, but the continental/regional average rests on few "
                "underlying functions, or the curve is applied outside the exact "
                "population it was fitted on."
            ),
            "low": (
                "Published but thin: a generic global average of two or three regional "
                "curves, or a small-literature-base fragility. Treat as an order of "
                "magnitude, not a point estimate."
            ),
            "note": (
                "Confidence describes how well-supported the curve is by its own source, "
                "not how well it fits any particular asset. Region and occupancy "
                "mismatch is a separate error, see gaps."
            ),
        },
        "units": {
            "y": "damage as a fraction of the relevant maximum damage value, 0-1",
            "x_units_seen": sorted({c["x_units"] for c in curves}),
            "max_damage": (
                "Euro per m2 at 2010 price level; Infrastructure is Euro per m of road, "
                "Agriculture is Euro per m2 of agricultural land. null = not reported."
            ),
        },
        "source_discrepancies": DISCREPANCIES,
        "curves": curves,
        "max_damage": {
            "source": f"{JRC_DOI}, Table 3-21 (per continent) and Table 3-22 (per country)",
            "units": "EUR/m2, 2010 price level (see units.max_damage for exceptions)",
            "classes": MAX_DAMAGE_CLASSES,
            "by_continent": JRC_MAX_DAMAGE_CONTINENT,
            "by_country": {
                k: dict(zip(MAX_DAMAGE_CLASSES, v))
                for k, v in JRC_MAX_DAMAGE_COUNTRY.items()
            },
            "caveat": (
                "The JRC report flags several of these as implausibly high relative to "
                "peers and in need of further research (notably North American "
                "agriculture at 662 EUR/m2). Values are averages over few observations "
                "per country. Treat as indicative."
            ),
        },
        "gaps": GAPS,
    }


# --------------------------------------------------------------------------------------
# Self-check
# --------------------------------------------------------------------------------------


def demo(doc: dict | None = None) -> dict:
    """Assert the dataset is well formed. Returns a small summary dict."""
    if doc is None:
        doc = json.loads(OUT.read_text())

    curves = doc["curves"]
    assert curves, "no curves at all"

    seen_ids = set()
    for c in curves:
        cid = c["id"]
        assert cid not in seen_ids, f"duplicate id {cid}"
        seen_ids.add(cid)

        x, y = c["x"], c["y"]
        assert x, f"{cid}: empty x"
        assert y, f"{cid}: empty y"
        assert len(x) == len(y), f"{cid}: x/y length mismatch {len(x)} vs {len(y)}"
        assert all(b > a for a, b in zip(x, x[1:])), f"{cid}: x not strictly ascending"
        assert all(0.0 <= v <= 1.0 for v in y), (
            f"{cid}: y outside [0,1] -> min {min(y)} max {max(y)}"
        )
        assert all(b >= a - 1e-9 for a, b in zip(y, y[1:])), (
            f"{cid}: y not monotonically non-decreasing"
        )

        assert c["source"] and len(c["source"]) > 20, f"{cid}: source too thin"
        assert c["confidence"] in ("high", "medium", "low"), f"{cid}: bad confidence"
        lo, hi = c["calibration_range"]
        assert lo <= hi, f"{cid}: bad calibration_range"
        assert lo == min(x) and hi == max(x), f"{cid}: calibration_range != x extent"
        assert c["hazard"] in ("flood", "wind"), f"{cid}: unexpected hazard"
        assert c["x_units"], f"{cid}: no x_units"

    assert doc["provenance"], "no provenance"
    assert doc["gaps"], "gaps list is empty -- that is itself a red flag"
    for g in doc["gaps"]:
        assert g["hazard"] and g["why"], "gap entry missing hazard or reason"

    # coverage the brief actually asked for
    jrc = [c for c in curves if c["id"].startswith("jrc_flood_")]
    continents = ["Africa", "Asia", "Europe", "North America", "Oceania", "South America"]
    for occ in ("Residential", "Commercial", "Industrial"):
        for region in continents:
            assert any(c["region"] == region and c["occupancy"] == occ for c in jrc), (
                f"missing JRC flood curve for {region}/{occ}"
            )
    assert len([c for c in curves if c["hazard"] == "wind"]) >= 10, "too few wind curves"

    from collections import Counter

    return {
        "n_curves": len(curves),
        "by_hazard": dict(Counter(c["hazard"] for c in curves)),
        "by_confidence": dict(Counter(c["confidence"] for c in curves)),
        "n_gaps": len(doc["gaps"]),
    }


def main() -> int:
    if "--check" in sys.argv:
        summary = demo()
    else:
        doc = build()
        OUT.write_text(json.dumps(doc, indent=2) + "\n")
        summary = demo(doc)
        print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")
    print("self-check PASSED:", json.dumps(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
